// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/message": {
            "get": {
                "summary": "List messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Limit, default 10",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Offset, default 0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ListMessageOut"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            },
            "post": {
                "summary": "Create new SMS",
                "parameters": [
                    {
                        "description": "Message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MessageIn"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.MessageOut"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/message/search": {
            "get": {
                "summary": "Search messages by phone number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phone number",
                        "name": "phoneNumber",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ListMessageOut"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/message/{messageUuid}": {
            "delete": {
                "summary": "Delete message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "messageUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/message/{messageUuid}/status": {
            "get": {
                "summary": "Get SMS status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "messageUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MessageStatusOut"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/sender": {
            "get": {
                "summary": "List senders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.SenderOut"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Create new sender",
                "parameters": [
                    {
                        "description": "New sender",
                        "name": "sender",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SenderIn"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.SenderOut"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/sender/check_connection/{senderUuid}": {
            "post": {
                "summary": "Check sender's login and password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sender ID",
                        "name": "senderUuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Login and password",
                        "name": "sender",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SenderIn"
                        }
                    }
                ],
                "responses": {
                    "204": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/sender/{senderUuid}": {
            "delete": {
                "summary": "Delete sender",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sender ID",
                        "name": "senderUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            },
            "patch": {
                "summary": "Edit sender",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sender ID",
                        "name": "senderUuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edited sender",
                        "name": "sender",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SenderOut"
                        }
                    }
                ],
                "responses": {
                    "204": {},
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorMessage": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ListMessageOut": {
            "type": "object",
            "properties": {
                "expirationTimeout": {
                    "type": "integer"
                },
                "messageText": {
                    "type": "string"
                },
                "messageType": {
                    "type": "string"
                },
                "messageUuid": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "sent": {
                    "type": "string"
                }
            }
        },
        "api.MessageIn": {
            "type": "object",
            "properties": {
                "expirationTimeout": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "messageText": {
                    "type": "string"
                },
                "messageType": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "senderName": {
                    "type": "string"
                }
            }
        },
        "api.MessageOut": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "messageUuid": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.MessageStatusOut": {
            "type": "object",
            "properties": {
                "messageUuid": {
                    "type": "string"
                },
                "sent": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.SenderIn": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.SenderOut": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "senderUuid": {
                    "type": "string"
                }
            }
        }
    },
    "x-extension-openapi": {
        "example": "value on a json format"
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "SMS-gate Mock",
	Description: "This is a simple emulator for SMS-gate",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
